app/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2021 - charityland
"""

from django.urls import path, re_path
from app import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.html', views.pages, name='pages'),

]

safecoin/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
#from main.views import IndexPageView, ChangeLanguageView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('user.urls')),
    path('members/', include("members.urls")),
    path('', include("app.urls")),

    #path('', IndexPageView.as_view(), name='index'),
    #path('i18n/', include('django.conf.urls.i18n')),
    #path('language/', ChangeLanguageView.as_view(), name='change_language'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views



from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'user'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    #path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),







    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('newsletter/', views.register_form, name='register_form'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.sign_up, name='signup'),
    path('reg', views.reg, name='reg'),
    path('user', views.user, name='user'),
    path('login', views.loginuser, name='loginuser'),
    path('test', views.test, name='test'),
    #path('loginpage/', views.loginpage, name='loginpage'),
    
    path('index/', views.index, name='index'),
    path('welcome/', views.register, name='register'),
    path("awelcome/", views.awelcome, name="awelcome"),
    path("takeme/", views.takeme, name="takeme"),
    
    
]

user/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
#from phonenumber_field.modelfields import PhoneNumberField


class Activation(models.Model):
     user = models.ForeignKey(User, on_delete=models.CASCADE)
     created_at = models.DateTimeField(auto_now_add=True)
     code = models.CharField(max_length=20, unique=True)
     email = models.EmailField(blank=True)




class sign_up(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    


class newsletter(models.Model):

    email = models.EmailField(max_length=70)
    full_name = models.CharField(max_length=70)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.full_name,self.email

    


# Create your models here.

user/views.py
from __future__ import unicode_literals
from .models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import newsletter_form, CreateUserForm, join_form
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from members.models import Agent



from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
     LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
     PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
 )
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
 )
from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
 )
from .models import Activation


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'user/log_in.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)


        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'user/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = True

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('Your account is successfully activated, proceed to Login.'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('You are successfully signed up!' 'Proceed to Login to your account'))

        return redirect('/welcome')


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account!'))

        return redirect('user:log_in')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'user/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = Activation()
        act.code = code
        act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('A new activation code has been sent to your email address.'))

        return redirect('user:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'user/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))

        if isinstance(uid, bytes):
            uid = uid.decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('user:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'user/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('user:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'user/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('user:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Change the email
        user = act.user
        user.email = act.email
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully changed your email!'))

        return redirect('user:change_email')


class RemindUsernameView(GuestOnlyView, FormView):
    template_name = 'user/remind_username.html'
    form_class = RemindUsernameForm

    def form_valid(self, form):
        user = form.user_cache
        send_forgotten_username_email(user.email, user.username)

        messages.success(self.request, _('Your username has been successfully sent to your email.'))

user/templates/user/agentwelcome.html
{% extends 'user/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load i18n %}

{% block content %}

<head>
  <meta charset='utf-8'>
  <title>Login & Register | Success</title>
</head>
<main>
  <!-- Section -->
  <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
      <div class="container">
          <p class="text-center"><a href="{% url 'agent_register' %}" class="text-gray-700"><i class="fas fa-angle-left mr-2"></i> Back to SignUp </a></p>
        <p class="text-center">Balance:</p>
              <h3 class="font-weight-bolder text-center">$ 0.00</h3>
             <div class="col-12 d-flex align-items-center justify-content-center">
                  <div class="mb-4 mb-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                      <div class="text-center text-md-center mb-4 mt-md-0">
                          <h1 class="mb-0 h3"><h1>Success! Welcome, {{ user.username }}!</h1></h1>
                          <div class="form-group mb-4">
                              <label for="username">You have applied for an agent!</label>
                            <h2 class="mb-0 h4"><h2>You are sponsored and your sponsor code is: (SPS{{ code }})</h2></h2>
                              <p>Click on deposit, select PPS and send your sponsor code to receive $ 6 verification fee.</p>
                              <div class="p">
                              <p>Note:</p>
                              <p>● Certified agents have access to our offices in various countries where availabe.</p>
                              <p>● They can join our  community to learn more about their roles and payments</p>
                              <p>● Both voluntary and paid agents need to perform a personal verification, 
                                however verifications are perform by authorised third party partner,
                                hence all agents have to pay for their verifications fees.</p>
                              <p>● All Voluntary agents are sponsored for their verifications.<p>
                            </div>
                              <div class="message1">
                                <h3>{% for message in messages %}
                                  <div class="message1">
                                  <strong class="message1">{{message}}</strong>
                                  </div>
                                  {% endfor %}</h3>
                              </div>  
                          <!-- End of Form -->
                      </form>
                      </div>
                  </div>
              </div>
          </div>
          <a href="{% url 'invoice' %}">
            <button type="submit" class="send_btn">Deposit verification fee</button>
          </a>
          <div class="text-success text-center">
            <a href="{% url 'checkidupload' %}">●Proceed to verification</a>
         </div>
      </div>
  </section>
</main>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title> Charityland.org</title>
      
      <link href="{% static 'user/css/bootstrap.min.css'%}">
      <script src="{% static 'user/css/bootstrap.mim.js' %}"></script>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'user/css/bootstrap.min.css'%}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'user/css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'user/images/Charitylogonew.png' %}" type="image/gif">
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'user/css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
      <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
      <link rel="icon" type="image/png" sizes="32x32" href="/static/assets/img/favicon/Charitylogonew.png">
      <link rel="icon" type="image/png" sizes="16x16" href="/static/assets/img/favicon/Charitylogonew.png">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
      <!-- end loader -->
      <!-- header -->
      <div class="an_container">
            <div class="an">
            <marquee behavior="" direction="left"><h2>welcome to charityland!</h2></marquee>
      
      </div>
         </div>
      <header>
         <div class="menu">
            <div class="header">
               <div class="container-fluid">
                  <div class="row">
                     <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                        <div class="full">
                           <div class="center-desk">
                              <div class="logo">
                                 <a href="/user/index"><img src={% static 'user/images/Charitylogonew.png' %} alt="Logo" /></a>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                        <div class="menu-area">
                           <div class="limit-box">
                              <nav class="main-menu">
                                 <ul class="menu-area-main">
                                    <li class="active"> <a href="/user/index">Home</a> </li>
                                    <li> <a href="{% url 'user:takeme' %}">Dashboard</a> </li>
                                    <li> <a href="/members/agt/profile">Agent Panel</a></li>
                                    <li> <a href="/members/agent/give">Vpp Panel</a> </li>
                                    <li> <a href="{% url 'user:sign_up' %}">Register</a> </li>
                                    <li> <a href="{% url 'user:log_in' %}">Login</a> </li>
                                    
                                 </ul>
                              </nav>
                           </div>
                        </div>  
                     </div>
                  </div>
               </div>
            </div>
            </div>
         </header>
              <!-- header inner -->
         <div class="head">
            <div  class="container">
               <div class="row ">
                  <div  class="col-md-6">
                     <ul class="email_call">
                        <li><a href="#"><img src="{% static 'user/icon/2.png' %}" alt="#"/>Call Us</a></li>
                        <li><a href="#"><img src="{% static 'user/icon/1.png' %}" alt="#"/>Email Us</a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
   <!-- body -->
   {% block content %}
   <body class="main-layout">
      <!-- loader  -->
      <div class="loader_bg">
        
         <!--<div class="loader"><img src="{% static 'user/loading.gif' %}" alt="#" /></div>-->
      </div>
   {% endblock %}
  <!-- contact -->
  <div id="request" class="contact">
   <div class="container-fluid">
      <div class="row">
        
            <div class="contact">
               <div class="titlepage">
                  <h2>Request a call back</h2>
               </div><br>
               <form class="request">
                  <div class="row">
                     <div class="col-sm-12">
                        <input class="contactus" placeholder="Name" type="text" name="Name">
                     </div>
                     <div class="col-sm-12">
                        <input class="contactus" placeholder="Phone Number" type="text" name="Phone Number">
                     </div>
                     <div class="col-sm-12">
                        <input class="contactus" placeholder="Email" type="text" name="Email">
                     </div>
                     <div class="col-sm-12">
                        <textarea class="textarea" placeholder="Message" type="text" name="Message"></textarea>
                     </div>
                     <div class="col-sm-12">
                        <button class="send">Send</button>
                     </div>
                  </div>
               </form>
            </div>
         </div>
         
      </div>
   </div>

<!-- end contact -->
 <div class="footer_container1">
    <div class="footer1">
       <div class="footer_heading1">
          <h2>About us</h2>
          <a href="">Partners</a>
          <a href="">Blog</a>
          <a href="">Roadmap</a>
          <a href="">Conditions</a>
       </div>
       <div class="footer_heading1">
         <h2>Contact us</h2>
         <a href="">Jobs</a>
         <a href="">Contact</a>
         <a href="">Support</a>
         <a href="">Sponsorship</a>
      </div>
      <div class="footer_heading1">
         <h2>Social Media</h2>
         <a href="">facebook</a>
         <a href="">Instagram</a>
         <a href="">Twitter</a>
         <a href="">Linkdin</a>
      </div>
      <div class="footer_email_form1">
         <h2>Join our newsletter</h2>
         <input type="text" id="footer_email1" placeholder="Enter your email address">
         <input type="submit" value="Subscribe" id="footer_email_btn1">
         </div>
    </div>
    <a href="{% url 'user:log_out' %}">Logout</a>
 </div>
 <!-- Javascript files-->
 <script src="{% static 'user/js/jquery.min.js' %}"></script>
 <script src="{% static 'user/js/popper.min.js' %}"></script>
 <script src="{% static 'user/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'user/js/jquery-3.0.0.min.js' %}"></script>
 <script src="{% static 'user/js/plugin.js' %}"></script>
 <!-- sidebar -->
 <script src="{% static 'user/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
 <script src="{% static 'user/js/custom.js' %}"></script>
 <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
 <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 11,
            center: {
                lat: 40.645037,
                lng: -73.880224
            },
        });
    
        var image = "{% static'user/images/maps-and-flags.png'}";
        var beachMarker = new google.maps.Marker({
            position: {
                lat: 40.645037,
                lng: -73.880224
            },
            map: map,
            icon: image
        });
    }
 </script>
 <!-- google map js -->
 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
 <!-- end google map js -->
</body>
</html>

user/templates/user/create.html
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <h2>Create an account</h2>
<form action="/user" method="POST">
    {%csrf_token%}
    {{form}}
    <button class="send_btn">Register</button>
</form>
{% endblock %}

user/templates/user/log_out.html
{% extends 'user/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load i18n %}

{% load i18n %}

{% block content %}


<main>
        <!-- Section -->
        <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
            <div class="container">
                <div class="col-12 d-flex align-items-center justify-content-center">
                <div class="mb-4 mb-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                    <div class="text-center text-md-center mb-4 mt-md-0">
                        <h3 class="mb-0 h3"><h3>{% trans 'Logged out' %}</h3></h3>
                        <div class="message1">
                        <p>
                            You have successfully logged out.
                        </p>
                            </div>
                                <ul>
                            <li>
            <a href="{% url 'user:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>
</div>
</div>
</div>
</div>
</section>

</main>
    

{% endblock %}

  

user/templates/user/loginpage.html
{% extends 'user/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<!--- model registration form extracted as html --->
<div class="res">
<div class="form-bg"></div>
<div class="form_head">
     <h2 class="form_title">Login to Charityland</h2>
</div>
<form action="/verify" method="POST">
     {% csrf_token %}
       <h2>Login</h2>
       <label for="log_email">Email:</label>
       <input type="text" id="email" name="email">
       <label for="log_password">Password:</label>
       <input type="password" id="password" name="password">
       {% for message in messages %}
<div class="message">
<strong class="message">{{message}}</strong>
</div>
{% endfor %}
       <button type="submit" name="button" value="login" class="send_btn">Login</button>
     </form>
     {% endblock %}

user/templates/user/profile.html
{% extends 'user/base.html' %}

{% block content %}
<h2>My profile</h2>>
<div>
    <div>
        
    </div>
    <h3>user</h3>
</div>
{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %}
{% block content %}
<!--- model registration form extracted as html --->
<div class="form-group">
     <form action="" method="POST">
     {%csrf_token%}
     {{form}}
     {{forms.errors}}
     <input type="submit">
     </form>
</div>
{% endblock %}

user/templates/user/restore_password_confirm.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    {% if validlink %}

        <p>
            {% trans 'Please enter your new password twice so we can verify you typed it in correctly.' %}
        </p>

        <form method="post">

            {% csrf_token %}
            {{form}}

            <button class="btn btn-success">{% trans 'Change' %}</button>

        </form>

    {% else %}

        <div class="alert alert-danger">
            {% trans 'The password reset link was invalid, possibly because it has already been used. Please request a new password reset.' %}
        </div>

    {% endif %}

{% endblock %}

user/templates/user/success.html
{% extends 'user/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load i18n %}

{% block content %}

<head>
  <meta charset='utf-8'>
  <title>Login & Register | Success</title>
</head>
<main>
  <!-- Section -->
  <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
      <div class="container">
          <p class="text-center"><a href="{% url 'user:sign_up' %}" class="text-gray-700"><i class="fas fa-angle-left mr-2"></i> Back to SignUp </a></p>
          
              <div class="col-12 d-flex align-items-center justify-content-center">
                  <div class="mb-4 mb-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                      <div class="text-center text-md-center mb-4 mt-md-0">
                          <h1 class="mb-0 h3"><h1>Success! Welcome, {{ user.username }}!</h1></h1>
                      
                          <div class="form-group mb-4">
                            <div>
                              <label for="username">You have successfully {{ achievement }}!</label>
                              <div class="message1">
                                <h3>{% for message in messages %}
                                  <div class="message1">
                                  <strong class="message1">{{message}}</strong>
                                  </div>
                                  {% endfor %}</h3>
                              </div>  
                          </div><br><br>
                          <!-- End of Form -->
                         <a href="{% url 'user:log_in' %}">
                          <button type="submit" class="send_btn1">login</button>
                        </a>
                      </form>
                      
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>

</main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}